/* Generated by kernel/scripts/isp/gen-blob-header.py --userspace. Do not edit. */
/*
 * Where ml-aed's constants live in the sensor tuning blob.
 *
 * Source: kernel/scripts/isp/blob-layout.toml in the kernel repo, the same file the ISP
 * driver's offsets are generated from. The layout is identical for every sensor the
 * vendor ships; which file to load is a board fact and arrives via --tuning.
 */
#ifndef ML_AED_BLOB_H
#define ML_AED_BLOB_H

#define MLAED_TUNING_SIZE           0xd6c58u

/* {gain Q8 u32, line_count u32}. Shipped configuration for the fixed FPV preview mode (1080p60, ceiling 1125 lines, gain ceiling 64.0), not something the vendor computes. Heap copy at state+0x68 agrees over all 366. */
#define MLAED_EXPOSURE_TABLE_OFF    0xb6524u
#define MLAED_EXPOSURE_TABLE_COUNT  366u
#define MLAED_EXPOSURE_TABLE_STRIDE 8u

/* {index u32, target u32}, the luma target knots. Heap state+0x4000+184. */
#define MLAED_TARGET_CURVE_OFF      0xba560u
#define MLAED_TARGET_CURVE_COUNT    5u
#define MLAED_TARGET_CURVE_STRIDE   8u

/* 512, 1024, 512, then the right-shift 11 at 0xba5f8. Heap state+0x4000+120. */
#define MLAED_ZONE_WEIGHTS_OFF      0xba5ecu
#define MLAED_ZONE_WEIGHTS_COUNT    4u

/* 50, the damping numerator; the law uses 50/256. Heap state+40. */
#define MLAED_DAMPING_OFF           0xba5fcu

/* 5, the settle tolerance in luma. Heap state+44. */
#define MLAED_TOLERANCE_OFF         0xba600u

/* 77.893997. In this file and nowhere in libmpp_service.so. Heap state+36. */
#define MLAED_LOG_LADDER_OFF        0xba620u

/* Mains anti-flicker selector: 0 unset, 1 = 50 Hz, 2 = 60 Hz, 3 = explicit off. Copied to heap state+0x414c by the AE tuning init at libmpp_service.so 0x2638f8/0x263918, and read by the gate inlined into aec_process_preview_and_video at 0x26a5e0, which calls aec_process_apply_flicker_50_60hz (0x25e728) to snap exposure to a whole number of mains half-periods and rescale gain by the inverse. A runtime override exists at AE state+0x5218 via CAM_PRA_SET_ANTIBANDING (0x73c). Shipped value 0, and the runtime word is never written on this unit, so the vendor applies no flicker constraint either. */
#define MLAED_ANTIBANDING_OFF       0xba624u

#endif /* ML_AED_BLOB_H */
