/*
 * ml-linkd-air.c - the air-unit (TX) role of ml-linkd.
 *
 * The air role speaks UDP on sdio0: it reads the battery voltage and SoC temperature over IIO and
 * transmits the vendor's :10000 status frames to the goggle at 10.0.0.1, and answers the goggle's
 * :20001 identity probe. Association is chip-autonomous from the artosyn_sdio insmod config.
 *
 * Under --rate-adapt it also runs the encoder rate governor (see the MCS section below), which is
 * the only part of the role that touches the bb control socket.
 */
#define _GNU_SOURCE                       /* strnlen (via mp-cmd.h) */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>
#include <unistd.h>
#include <fcntl.h>
#include <time.h>
#include <math.h>
#include <dirent.h>
#include <errno.h>
#include <poll.h>
#include <sys/time.h>
#include <netinet/in.h>
#include <arpa/inet.h>
#include <sys/socket.h>
#include <sys/un.h>

#include "bb-cmd.h"
#include "ml-linkd.h"
#include "ml-msp.h"
#include "mp-cmd.h"
#include "version.h"   /* ML_VERSION, generated by the Makefile from git describe */

#define AIR_ADC_IIO_NAME   "artosyn-adc"    /* IIO name of the SAR ADC provider (artosyn_adc.ko) */
#define AIR_TEMP_IIO_NAME  "temperature"    /* IIO name of the SoC temp sensor (artosyn_protemp.ko) */
#define AIR_BATT_CHANNEL   1                /* SAR ADC channel wired to the battery sense */

/* Battery divider on our IIO driver's calibrated pin scale: metered 4.24 V pack / 888 mV
 * in_voltage1_input (bench, P1_SKY). battery_mV = in_voltage1_input * this. */
#define AIR_BATT_DIVIDER   4.775f

#define AIR_STATUS_B_IVL_MS 160            /* 0x11 periodic (~6 Hz) */
#define AIR_STATUS_A_IVL_MS 1000           /* 0x09 version/info (~1 Hz) */

#define AIR_HW_VERSION_DEFAULT "V1.0"      /* used when --hw-version is absent */

static char g_air_batt_path[160];          /* .../in_voltageN_input (calibrated pin mV) */
static char g_air_temp_path[160];          /* .../in_temp_scale (whole degC) */

/* Read a single integer from a sysfs file. Returns the value, or dflt on any error. */
static int air_read_int(const char *path, int dflt)
{
    char buf[32];
    int fd;
    ssize_t n;

    if (path[0] == '\0') {
        return dflt;
    }

    fd = open(path, O_RDONLY);
    if (fd < 0) {
        return dflt;
    }

    n = read(fd, buf, sizeof buf - 1);
    close(fd);
    if (n <= 0) {
        return dflt;
    }

    buf[n] = '\0';
    return (int)strtol(buf, NULL, 10);
}

/* Find the IIO device directory whose name attribute equals want, writing its path into dir.
 * Returns 0 on a match, -1 otherwise. IIO device indices are not stable, so resolve by name. */
static int air_iio_find(const char *want, char *dir, size_t dirsz)
{
    DIR *d = opendir("/sys/bus/iio/devices");
    struct dirent *e;
    int found = -1;

    if (d == NULL) {
        return -1;
    }

    while ((e = readdir(d)) != NULL) {
        char namepath[192];
        char name[64];
        int fd;
        ssize_t n;

        if (strncmp(e->d_name, "iio:device", 10) != 0) {
            continue;
        }

        snprintf(namepath, sizeof namepath, "/sys/bus/iio/devices/%s/name", e->d_name);
        fd = open(namepath, O_RDONLY);
        if (fd < 0) {
            continue;
        }

        n = read(fd, name, sizeof name - 1);
        close(fd);
        if (n <= 0) {
            continue;
        }

        name[n] = '\0';
        while (n > 0 && (name[n - 1] == '\n' || name[n - 1] == ' ')) {
            name[--n] = '\0';
        }

        if (strcmp(name, want) == 0) {
            snprintf(dir, dirsz, "/sys/bus/iio/devices/%s", e->d_name);
            found = 0;
            break;
        }
    }

    closedir(d);
    return found;
}

/* Resolve the battery ADC channel and the temperature sensor to concrete sysfs read paths. Returns
 * 0 when both are found. Retried by air_main until the IIO providers have coldplugged. */
static int air_iio_init(void)
{
    char adc_dir[160];
    char temp_dir[160];

    g_air_batt_path[0] = '\0';
    g_air_temp_path[0] = '\0';

    if (air_iio_find(AIR_ADC_IIO_NAME, adc_dir, sizeof adc_dir) == 0) {
        snprintf(g_air_batt_path, sizeof g_air_batt_path, "%s/in_voltage%d_input",
                 adc_dir, AIR_BATT_CHANNEL);
    }

    if (air_iio_find(AIR_TEMP_IIO_NAME, temp_dir, sizeof temp_dir) == 0) {
        snprintf(g_air_temp_path, sizeof g_air_temp_path, "%s/in_temp_scale", temp_dir);
    }

    return (g_air_batt_path[0] != '\0' && g_air_temp_path[0] != '\0') ? 0 : -1;
}

/* Battery voltage in millivolts from the board ADC: the calibrated pin mV times the divider
 * (-1 sentinel until the ADC path resolves). */
static int air_adc_voltage_mv(void)
{
    int pin_mv = air_read_int(g_air_batt_path, -1);

    if (pin_mv < 0) {
        return -1;
    }

    return (int)lroundf((float)pin_mv * AIR_BATT_DIVIDER);
}

/* FC voltage wins while fresh, matching the vendor's >0x708 mV precedence rule. The ADC is read
 * every time so verbose logs can show both values on bench. */
static int air_voltage_mv(const struct ml_msp *msp, long now, int *adc_mv, int *fc_mv)
{
    *adc_mv = air_adc_voltage_mv();
    *fc_mv = ml_msp_fc_voltage_mv(msp, now);

    if (*fc_mv >= 0) {
        return *fc_mv;
    }

    return *adc_mv;
}

/* SoC junction temperature in whole degrees C (in_temp_scale carries the whole value directly). */
static int air_temp_c(void)
{
    return air_read_int(g_air_temp_path, 0);
}

/* Bind a UDP socket to the air unit's local address (10.0.0.100) on port. */
static int air_bind_local(int sock, int port)
{
    struct sockaddr_in local;

    memset(&local, 0, sizeof local);
    local.sin_family = AF_INET;
    inet_pton(AF_INET, AIR_ADDR, &local.sin_addr);
    local.sin_port = htons(port);

    return bind(sock, (struct sockaddr *)&local, sizeof local);
}

/* ---------------------------------------------------------------------------------------------
 * MCS-driven encoder rate adaptation.
 *
 * The vendor air recomputes its encoder target from the live RF link every time the MCS changes
 * (AR_FSM_TX_ProcessMcsChange @0x428b88 on a decrease, AR_FSM_TX_ProcessMcsChangeFinished @0x428fc8
 * on an increase), derives the number in AR_8030_TX_GetBitRate @0x4349b0 and applies it with
 * AR_LDRT_TX_VENC_SetRcParam. We reproduce the derivation and the drop-fast/rise-slow asymmetry,
 * poll GET_MCS instead of consuming an FSM event, and apply through ml-air-video's control socket.
 * Full RE and the offset-to-JSON-key mapping: plans/air-mcs-rate-adaptation.md.
 * ------------------------------------------------------------------------------------------- */

#define AIR_BB_NODE            "/dev/artosyn_sdio"
#define AIR_CTRL_SOCK          "/run/missinglynk/air-video.sock"

/* Mirrors of the vendor's cfg_transmedium.json knobs, values as captured from a stock air unit
 * (archive/out/air-probe/cfg_transmedium.json). Ar803xMinMcs is -1 there and MCS is never negative,
 * so the low-MCS branch is dead on a stock unit; it is kept because the constant is the switch. */
#define AIR_RATE_THROUGHPUT_RATE  0.7f      /* Ar803xThroutputRate */
#define AIR_RATE_LOW_MCS_RATE     0.8f      /* f32Ar803xThroutputRateLowMcs */
#define AIR_RATE_MAX_KBPS         20000     /* ArMaxBitRate */
#define AIR_RATE_MIN_MCS          (-1)      /* Ar803xMinMcs */
#define AIR_RATE_FALLBACK_KBPS    8000      /* the vendor's "use default bitrate 8Mbps" */
#define AIR_RATE_RATIO_PCT        100       /* runtime ratio; SetThroutputRate's default, never set */

/* The derived rate is a TOTAL across the two tiles the 1080p frame is split into; the control
 * socket takes a per-tile value. */
#define AIR_RATE_TILES            2

#define AIR_MCS_POLL_MS       200           /* GET_MCS cadence */
#define AIR_RATE_RISE_MS      1000          /* a higher MCS must hold this long before it is acted on */
#define AIR_RATE_OPEN_RETRY_MS 5000         /* bb-socket open retry cadence */
#define AIR_CTRL_TIMEOUT_MS   200           /* control-socket reply budget */
#define AIR_PROBE_DUMPS       20            /* raw GET_MCS replies to hexdump before going quiet */

struct air_rate {
    enum ml_rate_mode mode;
    int fd;                 /* bb socket, non-blocking; -1 until it opens */
    uint32_t seq;
    long last_poll_ms;
    long last_open_ms;
    int mcs;                /* last acted-on MCS, -1 = no sample yet */
    int pending_mcs;        /* higher MCS waiting out the settle window, -1 = none */
    long pending_since_ms;
    int applied_bps;        /* per-tile bps last pushed, 0 = none */
    int warned_open;
    int warned_ctrl;
    int probe_dumped;       /* raw reply hexdumps emitted so far (capped, see AIR_PROBE_DUMPS) */
};

/* The vendor derivation, kept in its original shape: the integer divide by 100 happens BEFORE the
 * multiply, so the throughput input is quantised to 100 kbps steps. Returns a total in kbps. */
static int air_rate_total_kbps(int mcs, int throughput_kbps)
{
    int kbps;

    if (throughput_kbps < 0) {
        throughput_kbps = 0;
    }

    if (AIR_RATE_MIN_MCS < mcs) {
        kbps = (int)((float)((throughput_kbps / 100) * AIR_RATE_RATIO_PCT)
                     * AIR_RATE_THROUGHPUT_RATE);
    } else {
        kbps = (int)((float)throughput_kbps * AIR_RATE_LOW_MCS_RATE);
    }

    if (kbps > AIR_RATE_MAX_KBPS) {
        kbps = AIR_RATE_MAX_KBPS;
    }

    return kbps != 0 ? kbps : AIR_RATE_FALLBACK_KBPS;
}

/* Push one per-tile bitrate to ml-air-video. Returns 0 when it answered "ok". */
static int air_rate_send(int bps_per_tile)
{
    const char *path = getenv("ML_AIR_CTRL");
    struct timeval tv = { .tv_sec = 0, .tv_usec = AIR_CTRL_TIMEOUT_MS * 1000 };
    struct sockaddr_un addr;
    char cmd[64];
    char reply[128];
    ssize_t n;
    int len;
    int fd;

    if (path == NULL || path[0] == '\0') {
        path = AIR_CTRL_SOCK;
    }

    if (strlen(path) >= sizeof addr.sun_path) {
        return -1;
    }

    fd = socket(AF_UNIX, SOCK_STREAM | SOCK_CLOEXEC, 0);
    if (fd < 0) {
        return -1;
    }

    setsockopt(fd, SOL_SOCKET, SO_RCVTIMEO, &tv, sizeof tv);
    setsockopt(fd, SOL_SOCKET, SO_SNDTIMEO, &tv, sizeof tv);

    memset(&addr, 0, sizeof addr);
    addr.sun_family = AF_UNIX;
    strncpy(addr.sun_path, path, sizeof addr.sun_path - 1);
    if (connect(fd, (struct sockaddr *)&addr, sizeof addr) != 0) {
        close(fd);
        return -1;
    }

    len = snprintf(cmd, sizeof cmd, "bitrate %d\n", bps_per_tile);
    if (write(fd, cmd, (size_t)len) != len) {
        close(fd);
        return -1;
    }

    n = read(fd, reply, sizeof reply - 1);
    close(fd);
    if (n <= 0) {
        return -1;
    }

    reply[n] = '\0';

    return strncmp(reply, "ok ", 3) == 0 ? 0 : -1;
}

/* Derive the target for @p mcs / @p throughput_kbps and apply it, unless it is already applied or
 * we are only probing. */
static void air_rate_apply(struct air_rate *r, int mcs, int throughput_kbps, const char *why)
{
    int total_kbps = air_rate_total_kbps(mcs, throughput_kbps);
    int bps = total_kbps * 1000 / AIR_RATE_TILES;

    if (r->mode == ML_RATE_PROBE) {
        printf(TAG " rate probe: %s mcs=%d throughput=%d kbps -> %d kbps total, %d bps/tile"
               " (not applied)\n", why, mcs, throughput_kbps, total_kbps, bps);
        fflush(stdout);
        return;
    }

    if (bps == r->applied_bps) {
        return;
    }

    if (air_rate_send(bps) != 0) {
        if (!r->warned_ctrl) {
            fprintf(stderr, TAG " rate: ml-air-video control socket not answering, retrying\n");
            r->warned_ctrl = 1;
        }
        return;
    }

    r->warned_ctrl = 0;
    r->applied_bps = bps;
    printf(TAG " rate: %s mcs=%d throughput=%d kbps -> %d bps/tile (%d kbps total)\n",
           why, mcs, throughput_kbps, bps, total_kbps);
    fflush(stdout);
}

/* One decoded GET_MCS sample. The first sample seeds the baseline; after that a DROP is acted on
 * immediately and a RISE only once the higher MCS has held for AIR_RATE_RISE_MS, which is what the
 * vendor's split between MCS_CHANGE and MCS_CHANGE_FINISHED amounts to. A change in throughput
 * alone does not move the rate - the vendor recomputes on MCS transitions only. */
static void air_rate_sample(struct air_rate *r, int mcs, int throughput_kbps, long now)
{
    if (g_verbose) {
        fprintf(stderr, TAG " mcs sample: mcs=%d throughput=%d kbps\n", mcs, throughput_kbps);
    }

    if (r->mcs < 0) {
        r->mcs = mcs;
        air_rate_apply(r, mcs, throughput_kbps, "baseline");
        return;
    }

    if (mcs < r->mcs) {
        r->mcs = mcs;
        r->pending_mcs = -1;
        air_rate_apply(r, mcs, throughput_kbps, "mcs drop");
        return;
    }

    if (mcs == r->mcs) {
        r->pending_mcs = -1;
        return;
    }

    if (r->pending_mcs != mcs) {
        r->pending_mcs = mcs;
        r->pending_since_ms = now;
        return;
    }

    if (now - r->pending_since_ms >= AIR_RATE_RISE_MS) {
        r->mcs = mcs;
        r->pending_mcs = -1;
        air_rate_apply(r, mcs, throughput_kbps, "mcs rise");
    }
}

/* Drain whatever the bb socket has and feed every GET_MCS reply to the sampler. Frames of any other
 * class (the ch05 chip log in particular) are discarded: on the air unit nothing else reads this
 * node. */
static void air_rate_drain(struct air_rate *r, long now)
{
    struct pollfd pfd = { .fd = r->fd, .events = POLLIN };
    uint8_t buf[4096];

    while (poll(&pfd, 1, 0) > 0 && (pfd.revents & POLLIN) != 0) {
        ssize_t n = read(r->fd, buf, sizeof buf);

        if (n <= 0) {
            return;
        }

        for (ssize_t i = 0; i + 18 < n; i++) {
            const uint8_t *pay;
            int plen;

            if (buf[i] != 0xaa) {
                continue;
            }

            plen = buf[i + 1] | (buf[i + 2] << 8);
            if (plen < MCS_OFF_THROUGHPUT + 4 || i + 18 + plen >= n) {
                continue;
            }

            if (buf[i + 18 + plen] != 0xbb || buf[i + 5] != BB_GET || buf[i + 8] != GET_MCS) {
                continue;
            }

            pay = buf + i + 18;

            if (r->mode == ML_RATE_PROBE && r->probe_dumped < AIR_PROBE_DUMPS) {
                r->probe_dumped++;
                printf(TAG " mcs reply (%d B):", plen);
                for (int k = 0; k < plen; k++) {
                    printf(" %02x", pay[k]);
                }
                printf("\n");
                fflush(stdout);
            }

            air_rate_sample(r, (int)pay[MCS_OFF_INDEX] - MCS_INDEX_BIAS,
                            (int)((uint32_t)pay[MCS_OFF_THROUGHPUT]
                                  | ((uint32_t)pay[MCS_OFF_THROUGHPUT + 1] << 8)
                                  | ((uint32_t)pay[MCS_OFF_THROUGHPUT + 2] << 16)
                                  | ((uint32_t)pay[MCS_OFF_THROUGHPUT + 3] << 24)),
                            now);
        }
    }
}

/* Service tick: open the bb socket if it is not up yet, poll GET_MCS on cadence, drain replies. */
static void air_rate_service(struct air_rate *r, long now)
{
    uint8_t frame[32];
    int len;

    if (r->mode == ML_RATE_OFF) {
        return;
    }

    if (r->fd < 0) {
        if (r->last_open_ms != 0 && now - r->last_open_ms < AIR_RATE_OPEN_RETRY_MS) {
            return;
        }

        r->last_open_ms = now;
        r->fd = open(AIR_BB_NODE, O_RDWR | O_NONBLOCK | O_CLOEXEC);
        if (r->fd < 0) {
            if (!r->warned_open) {
                fprintf(stderr, TAG " rate: open(%s): %s, retrying\n",
                        AIR_BB_NODE, strerror(errno));
                r->warned_open = 1;
            }
            return;
        }

        printf(TAG " rate: opened %s (%s)\n", AIR_BB_NODE,
               r->mode == ML_RATE_PROBE ? "probe, sends nothing" : "driving the encoder");
        fflush(stdout);
        r->warned_open = 0;
    }

    if (now - r->last_poll_ms >= AIR_MCS_POLL_MS) {
        r->last_poll_ms = now;
        len = bb_get(frame, GET_MCS, r->seq++);
        if (len > 0 && write(r->fd, frame, (size_t)len) != len) {
            fprintf(stderr, TAG " rate: GET_MCS write failed (%s), reopening\n", strerror(errno));
            close(r->fd);
            r->fd = -1;
            return;
        }
    }

    air_rate_drain(r, now);
}

/* The air role loop: transmit :10000 status telemetry to the goggle and answer its :20001 probe.
 * Sockets are (re)bound and the IIO providers (re)resolved each tick until sdio0 and the modules
 * are up, so it is safe to start before ml-rf-bringup has finished. */
struct air_canvas_tx {
    int sock;
    struct sockaddr_in *dst;
    int *bound;
};

static void air_send_canvas(const uint8_t *canvas, size_t len, void *ctx)
{
    struct air_canvas_tx *tx = ctx;
    struct timespec t;
    uint8_t frame[PKT_MAX];
    uint32_t stamp_us;

    if (tx->bound == NULL || !*tx->bound ||
        len > UINT8_MAX || MP_OFF_BODY + len + MP_TRAILER_LEN > sizeof frame) {
        return;
    }

    clock_gettime(CLOCK_MONOTONIC, &t);
    stamp_us = (uint32_t)(t.tv_sec * 1000000ULL + t.tv_nsec / 1000);
    sendto(tx->sock, frame, mp_msp_canvas(frame, canvas, (uint8_t)len, stamp_us), MSG_DONTWAIT,
           (struct sockaddr *)tx->dst, sizeof *tx->dst);
}

void air_main(const char *hw_version, const char *fc_tty, enum ml_rate_mode rate_mode)
{
    struct air_rate rate = { .mode = rate_mode, .fd = -1, .mcs = -1, .pending_mcs = -1 };
    int status_sock = socket(AF_INET, SOCK_DGRAM, 0);
    int hello_sock = socket(AF_INET, SOCK_DGRAM, 0);
    struct sockaddr_in goggle_status, goggle_hello;
    int status_bound = 0, hello_bound = 0, iio_ok = 0, warned_iio = 0;
    struct air_canvas_tx canvas_tx = { .sock = status_sock, .dst = &goggle_status,
                                       .bound = &status_bound };
    struct ml_msp msp;
    long last_a = 0, last_b = 0;
    int msp_warned = 0;
    int one = 1;

    if (hw_version == NULL || hw_version[0] == '\0') {
        hw_version = AIR_HW_VERSION_DEFAULT;
    }

    if (fc_tty == NULL || fc_tty[0] == '\0') {
        fc_tty = ML_MSP_DEFAULT_TTY;
    }

    ml_msp_init(&msp, air_send_canvas, &canvas_tx);

    setsockopt(status_sock, SOL_SOCKET, SO_REUSEADDR, &one, sizeof one);
    setsockopt(hello_sock, SOL_SOCKET, SO_REUSEADDR, &one, sizeof one);

    memset(&goggle_status, 0, sizeof goggle_status);
    goggle_status.sin_family = AF_INET;
    inet_pton(AF_INET, LOCAL_ADDR, &goggle_status.sin_addr);
    goggle_hello = goggle_status;
    goggle_status.sin_port = htons(PARAMS_PORT);
    goggle_hello.sin_port = htons(HELLO_PORT);

    printf(TAG " role=air: telemetry TX to %s:%d, FC MSP on %s\n",
           LOCAL_ADDR, PARAMS_PORT, fc_tty);
    fflush(stdout);

    while (g_run) {
        long now = now_ms();
        struct timespec t;
        uint32_t stamp_us;
        uint8_t frame[MP_STATUS_A_TOTAL];
        uint8_t rx[HELLO_LEN];
        ssize_t n;

        if (!status_bound && air_bind_local(status_sock, PARAMS_PORT) == 0) {
            status_bound = 1;
        }

        if (!hello_bound && air_bind_local(hello_sock, HELLO_PORT) == 0) {
            hello_bound = 1;
        }

        if (!iio_ok) {
            iio_ok = (air_iio_init() == 0);
            if (!iio_ok && !warned_iio) {
                fprintf(stderr, TAG " IIO not ready (artosyn_adc/protemp not loaded?), retrying\n");
                warned_iio = 1;
            }
        }

        if (msp.fd < 0 && ml_msp_open(&msp, fc_tty) != 0) {
            if (!msp_warned) {
                fprintf(stderr, TAG " FC MSP UART %s not ready, retrying\n", fc_tty);
                msp_warned = 1;
            }
        }

        clock_gettime(CLOCK_MONOTONIC, &t);
        stamp_us = (uint32_t)(t.tv_sec * 1000000ULL + t.tv_nsec / 1000);
        ml_msp_service(&msp, now);
        air_rate_service(&rate, now);

        /* 0x11 periodic (~6 Hz): FC status fields plus voltage with ADC fallback. */
        if (status_bound && now - last_b >= AIR_STATUS_B_IVL_MS) {
            int adc_mv;
            int fc_mv;
            int mv = air_voltage_mv(&msp, now, &adc_mv, &fc_mv);

            if (mv >= 0) {
                sendto(status_sock, frame,
                       mp_status_periodic(frame, msp.status.arm_flag, msp.status.mah_drawn_x10,
                                          (uint16_t)mv, stamp_us),
                       MSG_DONTWAIT, (struct sockaddr *)&goggle_status, sizeof goggle_status);
            }

            last_b = now;
        }

        /* 0x09 version/info (~1 Hz): hw/fw strings, voltage, air temperature. */
        if (status_bound && now - last_a >= AIR_STATUS_A_IVL_MS) {
            int adc_mv;
            int fc_mv;
            int mv = air_voltage_mv(&msp, now, &adc_mv, &fc_mv);
            int tc = air_temp_c();

            sendto(status_sock, frame,
                   mp_status_version(frame, hw_version, ML_VERSION,
                                     (uint16_t)(mv >= 0 ? mv : 0), (uint16_t)tc, stamp_us),
                   MSG_DONTWAIT, (struct sockaddr *)&goggle_status, sizeof goggle_status);

            if (g_verbose) {
                fprintf(stderr, TAG " tx status voltage=%d mV adc=%d mV fc=%d mV arm=%u mah_x10=%u temp=%d C\n",
                        mv, adc_mv, fc_mv, msp.status.arm_flag, msp.status.mah_drawn_x10, tc);
            }

            last_a = now;
        }

        /* Answer the goggle's :20001 identity probe: echo the 520-byte type-0 datagram back verbatim
         * with byte[0]=0x01 (the type-1 identity); the goggle replies with the byte[0]=0x02 ACK. */
        while (hello_bound &&
               (n = recvfrom(hello_sock, rx, sizeof rx, MSG_DONTWAIT, NULL, NULL)) > 0) {
            if (rx[0] == 0x00) {
                rx[0] = 0x01;
                sendto(hello_sock, rx, n, MSG_DONTWAIT,
                       (struct sockaddr *)&goggle_hello, sizeof goggle_hello);
            }
        }

        /* Drain the goggle's :10000 datagrams (params request + config) to keep the receive buffer
         * clear. */
        if (status_bound) {
            uint8_t junk[PKT_MAX];

            while (recvfrom(status_sock, junk, sizeof junk, MSG_DONTWAIT, NULL, NULL) > 0) {
                /* discard */
            }
        }

        usleep(UDP_TICK_US);
    }

    close(status_sock);
    close(hello_sock);
    ml_msp_close(&msp);

    if (rate.fd >= 0) {
        close(rate.fd);
    }

    printf(TAG " role=air clean stop\n");
}
