/*
 * ml-linkd-air.c - the air-unit (TX) role of ml-linkd.
 *
 * The air role speaks UDP on sdio0: it reads the battery voltage and SoC temperature over IIO and
 * transmits the vendor's :10000 status frames to the goggle at 10.0.0.1, and answers the goggle's
 * :20001 identity probe. Association is chip-autonomous from the artosyn_sdio insmod config.
 */
#define _GNU_SOURCE                       /* strnlen (via mp-cmd.h) */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>
#include <unistd.h>
#include <fcntl.h>
#include <time.h>
#include <math.h>
#include <dirent.h>
#include <netinet/in.h>
#include <arpa/inet.h>
#include <sys/socket.h>

#include "ml-linkd.h"
#include "mp-cmd.h"
#include "version.h"   /* ML_VERSION, generated by the Makefile from git describe */

#define AIR_ADC_IIO_NAME   "artosyn-adc"    /* IIO name of the SAR ADC provider (artosyn_adc.ko) */
#define AIR_TEMP_IIO_NAME  "temperature"    /* IIO name of the SoC temp sensor (artosyn_protemp.ko) */
#define AIR_BATT_CHANNEL   1                /* SAR ADC channel wired to the battery sense */

/* Battery divider on our IIO driver's calibrated pin scale: metered 4.24 V pack / 888 mV
 * in_voltage1_input (bench, P1_SKY). battery_mV = in_voltage1_input * this. */
#define AIR_BATT_DIVIDER   4.775f

#define AIR_STATUS_B_IVL_MS 160            /* 0x11 periodic (~6 Hz) */
#define AIR_STATUS_A_IVL_MS 1000           /* 0x09 version/info (~1 Hz) */

#define AIR_HW_VERSION_DEFAULT "V1.0"      /* used when --hw-version is absent */

static char g_air_batt_path[160];          /* .../in_voltageN_input (calibrated pin mV) */
static char g_air_temp_path[160];          /* .../in_temp_scale (whole degC) */

/* Read a single integer from a sysfs file. Returns the value, or dflt on any error. */
static int air_read_int(const char *path, int dflt)
{
    char buf[32];
    int fd;
    ssize_t n;

    if (path[0] == '\0') {
        return dflt;
    }

    fd = open(path, O_RDONLY);
    if (fd < 0) {
        return dflt;
    }

    n = read(fd, buf, sizeof buf - 1);
    close(fd);
    if (n <= 0) {
        return dflt;
    }

    buf[n] = '\0';
    return (int)strtol(buf, NULL, 10);
}

/* Find the IIO device directory whose name attribute equals want, writing its path into dir.
 * Returns 0 on a match, -1 otherwise. IIO device indices are not stable, so resolve by name. */
static int air_iio_find(const char *want, char *dir, size_t dirsz)
{
    DIR *d = opendir("/sys/bus/iio/devices");
    struct dirent *e;
    int found = -1;

    if (d == NULL) {
        return -1;
    }

    while ((e = readdir(d)) != NULL) {
        char namepath[192];
        char name[64];
        int fd;
        ssize_t n;

        if (strncmp(e->d_name, "iio:device", 10) != 0) {
            continue;
        }

        snprintf(namepath, sizeof namepath, "/sys/bus/iio/devices/%s/name", e->d_name);
        fd = open(namepath, O_RDONLY);
        if (fd < 0) {
            continue;
        }

        n = read(fd, name, sizeof name - 1);
        close(fd);
        if (n <= 0) {
            continue;
        }

        name[n] = '\0';
        while (n > 0 && (name[n - 1] == '\n' || name[n - 1] == ' ')) {
            name[--n] = '\0';
        }

        if (strcmp(name, want) == 0) {
            snprintf(dir, dirsz, "/sys/bus/iio/devices/%s", e->d_name);
            found = 0;
            break;
        }
    }

    closedir(d);
    return found;
}

/* Resolve the battery ADC channel and the temperature sensor to concrete sysfs read paths. Returns
 * 0 when both are found. Retried by air_main until the IIO providers have coldplugged. */
static int air_iio_init(void)
{
    char adc_dir[160];
    char temp_dir[160];

    g_air_batt_path[0] = '\0';
    g_air_temp_path[0] = '\0';

    if (air_iio_find(AIR_ADC_IIO_NAME, adc_dir, sizeof adc_dir) == 0) {
        snprintf(g_air_batt_path, sizeof g_air_batt_path, "%s/in_voltage%d_input",
                 adc_dir, AIR_BATT_CHANNEL);
    }

    if (air_iio_find(AIR_TEMP_IIO_NAME, temp_dir, sizeof temp_dir) == 0) {
        snprintf(g_air_temp_path, sizeof g_air_temp_path, "%s/in_temp_scale", temp_dir);
    }

    return (g_air_batt_path[0] != '\0' && g_air_temp_path[0] != '\0') ? 0 : -1;
}

/* Battery voltage in millivolts: the calibrated ADC pin mV times the board divider (-1 sentinel
 * until the ADC path resolves). */
static int air_voltage_mv(void)
{
    int pin_mv = air_read_int(g_air_batt_path, -1);

    if (pin_mv < 0) {
        return -1;
    }

    return (int)lroundf((float)pin_mv * AIR_BATT_DIVIDER);
}

/* SoC junction temperature in whole degrees C (in_temp_scale carries the whole value directly). */
static int air_temp_c(void)
{
    return air_read_int(g_air_temp_path, 0);
}

/* Bind a UDP socket to the air unit's local address (10.0.0.100) on port. */
static int air_bind_local(int sock, int port)
{
    struct sockaddr_in local;

    memset(&local, 0, sizeof local);
    local.sin_family = AF_INET;
    inet_pton(AF_INET, AIR_ADDR, &local.sin_addr);
    local.sin_port = htons(port);

    return bind(sock, (struct sockaddr *)&local, sizeof local);
}

/* The air role loop: transmit :10000 status telemetry to the goggle and answer its :20001 probe.
 * Sockets are (re)bound and the IIO providers (re)resolved each tick until sdio0 and the modules
 * are up, so it is safe to start before ml-rf-bringup has finished. */
void air_main(const char *hw_version)
{
    int status_sock = socket(AF_INET, SOCK_DGRAM, 0);
    int hello_sock = socket(AF_INET, SOCK_DGRAM, 0);
    struct sockaddr_in goggle_status, goggle_hello;
    long last_a = 0, last_b = 0;
    int status_bound = 0, hello_bound = 0, iio_ok = 0, warned_iio = 0;
    int one = 1;

    if (hw_version == NULL || hw_version[0] == '\0') {
        hw_version = AIR_HW_VERSION_DEFAULT;
    }

    setsockopt(status_sock, SOL_SOCKET, SO_REUSEADDR, &one, sizeof one);
    setsockopt(hello_sock, SOL_SOCKET, SO_REUSEADDR, &one, sizeof one);

    memset(&goggle_status, 0, sizeof goggle_status);
    goggle_status.sin_family = AF_INET;
    inet_pton(AF_INET, LOCAL_ADDR, &goggle_status.sin_addr);
    goggle_hello = goggle_status;
    goggle_status.sin_port = htons(PARAMS_PORT);
    goggle_hello.sin_port = htons(HELLO_PORT);

    printf(TAG " role=air: telemetry TX to %s:%d\n", LOCAL_ADDR, PARAMS_PORT);
    fflush(stdout);

    while (g_run) {
        long now = now_ms();
        struct timespec t;
        uint32_t stamp_us;
        uint8_t frame[MP_STATUS_A_TOTAL];
        uint8_t rx[HELLO_LEN];
        ssize_t n;

        if (!status_bound && air_bind_local(status_sock, PARAMS_PORT) == 0) {
            status_bound = 1;
        }

        if (!hello_bound && air_bind_local(hello_sock, HELLO_PORT) == 0) {
            hello_bound = 1;
        }

        if (!iio_ok) {
            iio_ok = (air_iio_init() == 0);
            if (!iio_ok && !warned_iio) {
                fprintf(stderr, TAG " IIO not ready (artosyn_adc/protemp not loaded?), retrying\n");
                warned_iio = 1;
            }
        }

        clock_gettime(CLOCK_MONOTONIC, &t);
        stamp_us = (uint32_t)(t.tv_sec * 1000000ULL + t.tv_nsec / 1000);

        /* 0x11 periodic (~6 Hz): voltage only. Skip until the ADC reads. */
        if (status_bound && now - last_b >= AIR_STATUS_B_IVL_MS) {
            int mv = air_voltage_mv();

            if (mv >= 0) {
                sendto(status_sock, frame, mp_status_periodic(frame, (uint16_t)mv, stamp_us),
                       MSG_DONTWAIT, (struct sockaddr *)&goggle_status, sizeof goggle_status);
            }

            last_b = now;
        }

        /* 0x09 version/info (~1 Hz): hw/fw strings, voltage, air temperature. */
        if (status_bound && now - last_a >= AIR_STATUS_A_IVL_MS) {
            int mv = air_voltage_mv();
            int tc = air_temp_c();

            sendto(status_sock, frame,
                   mp_status_version(frame, hw_version, ML_VERSION,
                                     (uint16_t)(mv >= 0 ? mv : 0), (uint16_t)tc, stamp_us),
                   MSG_DONTWAIT, (struct sockaddr *)&goggle_status, sizeof goggle_status);

            if (g_verbose) {
                fprintf(stderr, TAG " tx status voltage=%d mV temp=%d C\n", mv, tc);
            }

            last_a = now;
        }

        /* Answer the goggle's :20001 identity probe: echo the 520-byte type-0 datagram back verbatim
         * with byte[0]=0x01 (the type-1 identity); the goggle replies with the byte[0]=0x02 ACK. */
        while (hello_bound &&
               (n = recvfrom(hello_sock, rx, sizeof rx, MSG_DONTWAIT, NULL, NULL)) > 0) {
            if (rx[0] == 0x00) {
                rx[0] = 0x01;
                sendto(hello_sock, rx, n, MSG_DONTWAIT,
                       (struct sockaddr *)&goggle_hello, sizeof goggle_hello);
            }
        }

        /* Drain the goggle's :10000 datagrams (params request + config) to keep the receive buffer
         * clear. */
        if (status_bound) {
            uint8_t junk[PKT_MAX];

            while (recvfrom(status_sock, junk, sizeof junk, MSG_DONTWAIT, NULL, NULL) > 0) {
                /* discard */
            }
        }

        usleep(UDP_TICK_US);
    }

    close(status_sock);
    close(hello_sock);
    printf(TAG " role=air clean stop\n");
}
